name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  outdated-minor:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.2-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install bundler
        run: gem install bundler
      - name: List outdated gems
        run: |
          bundle outdated --minor || true