name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  outdated-minor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List outdated minor versions
        run: |
          gem install bundler
          bundle install
          bundle outdated --minor